/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AdsDottxtRouteImport } from './routes/ads[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriaSlugRouteImport } from './routes/historia.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsDottxtRoute = AdsDottxtRouteImport.update({
  id: '/ads.txt',
  path: '/ads.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaSlugRoute = HistoriaSlugRouteImport.update({
  id: '/historia/$slug',
  path: '/historia/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/historia/$slug': typeof HistoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/historia/$slug': typeof HistoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads.txt': typeof AdsDottxtRoute
  '/contato': typeof ContatoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/historia/$slug': typeof HistoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads.txt'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/categoria/$slug'
    | '/historia/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads.txt'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/categoria/$slug'
    | '/historia/$slug'
  id:
    | '__root__'
    | '/'
    | '/ads.txt'
    | '/contato'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/termos'
    | '/categoria/$slug'
    | '/historia/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsDottxtRoute: typeof AdsDottxtRoute
  ContatoRoute: typeof ContatoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  HistoriaSlugRoute: typeof HistoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads.txt': {
      id: '/ads.txt'
      path: '/ads.txt'
      fullPath: '/ads.txt'
      preLoaderRoute: typeof AdsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia/$slug': {
      id: '/historia/$slug'
      path: '/historia/$slug'
      fullPath: '/historia/$slug'
      preLoaderRoute: typeof HistoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsDottxtRoute: AdsDottxtRoute,
  ContatoRoute: ContatoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  HistoriaSlugRoute: HistoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
